title: Begoña Perez Rodriguez - 3D artist and designer
description: >
  **I am Begoña**, a 3D artist and designer.
copyright: CreaByBego
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: "begognasportfolio"
facebook_username: "creabybego"
twitter_username:
linkedin_username: "begonaperez"
instagram_username:
pinterest_username:
flickr_username:
github_username: "begogna"
feed_icon:
etsy_username: "CreaByBego"
sketchfab_username: "begogna"
shapeways_hireme: "designer/begogna/hire-me"
imaterialise_username: "begogna"
skype_username: "begogna"

email: "begona.perezrodriguez@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
collections:
  sections:
    output: true
    permalink: /:path/
  items:
    output: true
    permalink: /:collection/:path/
